name: Release Docker image

on:
  repository_dispatch:
    types:
      - release-triggered
  workflow_dispatch:
    inputs:
      tag:
        description: 'Custom Docker image tag (note - this won't update the VERSION file and is for non-prod releases only)
        required: false
      version:
        description: 'Custom version (sets the first part of the Docker tag - this will update the VERSION file)
        required: false
      push_to_latest:
        description: 'Should push to latest'
        type: boolean
        default: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ruby/setup-ruby@v1
      - run: "bundle install"

      - name: Release image
        run: script/release-workflow/run.sh
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
          TAG: ${{ github.event.inputs.tag }}
          VERSION: ${{ github.event.inputs.version }}
          PUSH_TO_LATEST: ${{ github.event.inputs.push_to_latest }}
